### ISSUE TITLE
500 Internal server Issue

### ISSUE THREAD

**Issue by StalinNeelamegam** [Paubox/paubox-csharp#5]
Hi, 
We are getting an Internal server error while sending an email using paubox Rest API. When "ForceSecureNotification" setting is set to false, but, email delivered successfully.  Please find the attached video for details.

Thanks,
Stalin (Cleveland Clinic Wellness)
[500 -Internal server error.zip](https://github.com/Paubox/paubox-csharp/files/3280301/500.-Internal.server.error.zip)

**Comment by TomatoOmelette** [comment]
Thanks for this info. We are looking into the issue today.

**Comment by TomatoOmelette** [comment]
We believe this issue is resolved. Can you test again? Thank you.

**Comment by StalinNeelamegam** [comment]
Thank you for your response. I will check and let you know.

**Comment by StalinNeelamegam** [comment]
Thank you ! It's working fine.

**Comment by vighneshtrivedi2004** [comment]
Thanks Stalin.
